# Generated by Django 5.2.1 on 2025-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercieMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.IntegerField(default=0)),
                ('TextEnglish', models.CharField(max_length=255)),
                ('TextPersian', models.CharField(max_length=255)),
            ],
        ),
    ]
