# Generated by Django 5.2.1 on 2025-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AInutritions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.IntegerField(default=0)),
                ('TextEnglish', models.CharField(max_length=511)),
                ('Veggies', models.CharField(max_length=255)),
                ('Protein', models.CharField(max_length=255)),
                ('Juice', models.CharField(max_length=255)),
            ],
        ),
    ]
